version: '3.7'

services:

  sample-prod:
    container_name: chat-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'


# https://mherman.org/blog/dockerizing-a-react-app/