version: '3.7'

services:

  sample-prod:
    container_name: blog-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8800:80'


# https://mherman.org/blog/dockerizing-a-react-app/